### PR TITLE
feat: Automatic PyPI Publishing using Tags

### LINKED ISSUE #2: Automatic Release to PyPI Not Triggered
Description: The current version of execexam lacks an automated workflow for releasing new versions to PyPI. This leads to a manual process for publishing updates, which increases the risk of versioning inconsistencies, delayed releases, and potential human error.

Expected Behavior: Upon pushing a new release an automated workflow should trigger. These should run tests automatically, build the package, and upload the package to PyPI automatically via CI/CD (CI/CD stands for Continuous Integration and Continuous Deployment)

Actual Behavior: No automated release process is currently set up leading to delays and the incapability for other team members to push.

Proposed Solution: Implement a CI/CD pipeline that triggers tests on push, builds deployment process to PyPI when a release, and has integration with PyPI using secure credentials

### PR DESCRIPTION
**Pull request by PCain02**
1. Make sure the title is descriptive of what the PR includes. Don't mention
issue names/numbers; save that for the description.

2. List the names of those who contributed to the project.
@PCain02

3. Link the issue the pull request is meant to fix/resolve.
Closes https://github.com/GatorEducator/execexam/issues/2

4. Describe the contents and goal of the pull request.
This PR adds the ability to publish to PyPI automatically when using tags. publish.yml and test-publish.yml were the main targets of the PR. The lowercase t tag will be used for test publishing and the lowercase v tag is for real publishing. They should look like t0.3.1 and v0.3.1

I also deleted the empty test files and the "Rebekah Test" print statement so it would pass the lining checks and make it so we can merge into the main execexam.

5. What operating systems has this been tested on? How were these tests conducted?
Windows 10 but I would like it reviewed on MacOS and Linux before pushing. The tests were conducted by running the following commands (replace the version number with the actual version next in line):

poetry version 0.3.1
git add pyproject.toml
git commit -m "Chore: Bump version to 0.3.1"
git tag t0.3.1
git push origin t0.3.1

You will know it worked if [Test PyPI](https://test.pypi.org/project/execexam/) has updated the version number

Note: we won't be able to use the v tag until this is in the actual execexam and Professor Kapfhammer's secret key has been added.

6. Add all labels that apply. (e.g., documentation, ready-for-review)
Infrastructure

7. Will coverge be maintained/increased?
This does not affect coverage.

8. Include a code block and/or screenshots displaying the functionality of your
feature, if applicable/possible.

PS C:\Users\Palla\Documents\GitHub\execexam> poetry version 0.3.30
Bumping version from 0.3.30 to 0.3.30
PS C:\Users\Palla\Documents\GitHub\execexam> git add .
PS C:\Users\Palla\Documents\GitHub\execexam> git commit -m 'chore: bump version to 0.3.30 test'
PS C:\Users\Palla\Documents\GitHub\execexam> git tag t0.3.30      
PS C:\Users\Palla\Documents\GitHub\execexam> git push origin t0.3.30
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
To https://github.com/PCain02/execexam.git
* [new tag]         t0.3.30 -> t0.3.30
@rebekahrudd @dyga01

### CODE REVIEW

**Comment by rebekahrudd** [comment]
I followed these steps on Linux and it all worked in the terminal but once pushed to origin main the Action did not show up.
Screenshot from 2024-09-20 10-40-58

**Review by dyga01 — APPROVED** [review]
This code works for publishing a test version to PyPI on Mac. I just think that we need to ensure that the -v tag works in addition to this whenever Professor Kapfhammer's secret key gets added.

**Review by hannahb09 — COMMENTED** [review]
Automatic PyPI Publishing using Tags worked on linux. I was able to bump to 0.3.36.

**Review by hannahb09 — APPROVED** [review]
looks good to me.

**Pull request merged**
